//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.11 at 08:27:51 PM CET 
//


package at.qualisign.metrics.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SuperClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OwningPackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Metrics" type="{jhawk}ClassMetricsType"/>
 *         &lt;element name="Methods" type="{jhawk}MethodsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassType", propOrder = {
    "superClass",
    "owningPackage",
    "className",
    "metrics",
    "methods"
})
public class ClassType {

    @XmlElement(name = "SuperClass", required = true)
    protected String superClass;
    @XmlElement(name = "OwningPackage", required = true)
    protected String owningPackage;
    @XmlElement(name = "ClassName", required = true)
    protected String className;
    @XmlElement(name = "Metrics", required = true)
    protected ClassMetricsType metrics;
    @XmlElement(name = "Methods")
    protected MethodsType methods;

    /**
     * Gets the value of the superClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperClass() {
        return superClass;
    }

    /**
     * Sets the value of the superClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperClass(String value) {
        this.superClass = value;
    }

    /**
     * Gets the value of the owningPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwningPackage() {
        return owningPackage;
    }

    /**
     * Sets the value of the owningPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwningPackage(String value) {
        this.owningPackage = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link ClassMetricsType }
     *     
     */
    public ClassMetricsType getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassMetricsType }
     *     
     */
    public void setMetrics(ClassMetricsType value) {
        this.metrics = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodsType }
     *     
     */
    public MethodsType getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodsType }
     *     
     */
    public void setMethods(MethodsType value) {
        this.methods = value;
    }

}
