//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.11 at 08:27:51 PM CET 
//


package at.qualisign.metrics.jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for MethodMetricsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodMetricsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loc" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="cyclomaticComplexity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfArguments" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfCasts" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfComments" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfCommentLines" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfExpressions" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfVariableDeclarations" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfLoops" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfOperands" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfOperators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfStatements" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="numberOfVariableReferences" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="totalNesting" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="maxDepthOfNesting" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="halsteadLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="halsteadVocabulary" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="halsteadBugs" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="halsteadDifficulty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="halsteadEffort" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="halsteadVolume" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="classesReferenced" type="{jhawk}classesReferencedType" minOccurs="0"/>
 *         &lt;element name="externalMethodsCalled" type="{jhawk}externalMethodsCalledType" minOccurs="0"/>
 *         &lt;element name="localMethods" type="{jhawk}localMethodsType" minOccurs="0"/>
 *         &lt;element name="variablesDeclared" type="{jhawk}variablesDeclaredType" minOccurs="0"/>
 *         &lt;element name="variablesReferenced" type="{jhawk}variablesReferencedType" minOccurs="0"/>
 *         &lt;element name="instanceVariablesReferenced" type="{jhawk}instanceVariablesReferencedType" minOccurs="0"/>
 *         &lt;element name="localInstanceVariablesReferenced" type="{jhawk}localInstanceVariablesReferencedType" minOccurs="0"/>
 *         &lt;element name="exceptionsReferenced" type="{jhawk}exceptionsReferencedType" minOccurs="0"/>
 *         &lt;element name="exceptionsThrown" type="{jhawk}exceptionsThrownType" minOccurs="0"/>
 *         &lt;element name="arguments" type="{jhawk}argumentsType" minOccurs="0"/>
 *         &lt;element name="modifiers" type="{jhawk}modifiersType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodMetricsType", propOrder = {

})
public class MethodMetricsType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger loc;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cyclomaticComplexity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfArguments;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfCasts;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfComments;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfCommentLines;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfExpressions;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfVariableDeclarations;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfLoops;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfOperands;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfOperators;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfStatements;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfVariableReferences;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalNesting;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxDepthOfNesting;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger halsteadLength;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger halsteadVocabulary;
    protected float halsteadBugs;
    protected float halsteadDifficulty;
    protected float halsteadEffort;
    protected float halsteadVolume;
    protected ClassesReferencedType classesReferenced;
    protected ExternalMethodsCalledType externalMethodsCalled;
    protected LocalMethodsType localMethods;
    protected VariablesDeclaredType variablesDeclared;
    protected VariablesReferencedType variablesReferenced;
    protected InstanceVariablesReferencedType instanceVariablesReferenced;
    protected LocalInstanceVariablesReferencedType localInstanceVariablesReferenced;
    protected ExceptionsReferencedType exceptionsReferenced;
    protected ExceptionsThrownType exceptionsThrown;
    protected ArgumentsType arguments;
    protected ModifiersType modifiers;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoc() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoc(BigInteger value) {
        this.loc = value;
    }

    /**
     * Gets the value of the cyclomaticComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCyclomaticComplexity() {
        return cyclomaticComplexity;
    }

    /**
     * Sets the value of the cyclomaticComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCyclomaticComplexity(BigInteger value) {
        this.cyclomaticComplexity = value;
    }

    /**
     * Gets the value of the numberOfArguments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfArguments() {
        return numberOfArguments;
    }

    /**
     * Sets the value of the numberOfArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfArguments(BigInteger value) {
        this.numberOfArguments = value;
    }

    /**
     * Gets the value of the numberOfCasts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCasts() {
        return numberOfCasts;
    }

    /**
     * Sets the value of the numberOfCasts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCasts(BigInteger value) {
        this.numberOfCasts = value;
    }

    /**
     * Gets the value of the numberOfComments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfComments() {
        return numberOfComments;
    }

    /**
     * Sets the value of the numberOfComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfComments(BigInteger value) {
        this.numberOfComments = value;
    }

    /**
     * Gets the value of the numberOfCommentLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCommentLines() {
        return numberOfCommentLines;
    }

    /**
     * Sets the value of the numberOfCommentLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCommentLines(BigInteger value) {
        this.numberOfCommentLines = value;
    }

    /**
     * Gets the value of the numberOfExpressions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfExpressions() {
        return numberOfExpressions;
    }

    /**
     * Sets the value of the numberOfExpressions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfExpressions(BigInteger value) {
        this.numberOfExpressions = value;
    }

    /**
     * Gets the value of the numberOfVariableDeclarations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfVariableDeclarations() {
        return numberOfVariableDeclarations;
    }

    /**
     * Sets the value of the numberOfVariableDeclarations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfVariableDeclarations(BigInteger value) {
        this.numberOfVariableDeclarations = value;
    }

    /**
     * Gets the value of the numberOfLoops property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLoops() {
        return numberOfLoops;
    }

    /**
     * Sets the value of the numberOfLoops property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLoops(BigInteger value) {
        this.numberOfLoops = value;
    }

    /**
     * Gets the value of the numberOfOperands property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOperands() {
        return numberOfOperands;
    }

    /**
     * Sets the value of the numberOfOperands property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOperands(BigInteger value) {
        this.numberOfOperands = value;
    }

    /**
     * Gets the value of the numberOfOperators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOperators() {
        return numberOfOperators;
    }

    /**
     * Sets the value of the numberOfOperators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOperators(BigInteger value) {
        this.numberOfOperators = value;
    }

    /**
     * Gets the value of the numberOfStatements property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfStatements() {
        return numberOfStatements;
    }

    /**
     * Sets the value of the numberOfStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfStatements(BigInteger value) {
        this.numberOfStatements = value;
    }

    /**
     * Gets the value of the numberOfVariableReferences property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfVariableReferences() {
        return numberOfVariableReferences;
    }

    /**
     * Sets the value of the numberOfVariableReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfVariableReferences(BigInteger value) {
        this.numberOfVariableReferences = value;
    }

    /**
     * Gets the value of the totalNesting property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNesting() {
        return totalNesting;
    }

    /**
     * Sets the value of the totalNesting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNesting(BigInteger value) {
        this.totalNesting = value;
    }

    /**
     * Gets the value of the maxDepthOfNesting property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDepthOfNesting() {
        return maxDepthOfNesting;
    }

    /**
     * Sets the value of the maxDepthOfNesting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDepthOfNesting(BigInteger value) {
        this.maxDepthOfNesting = value;
    }

    /**
     * Gets the value of the halsteadLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHalsteadLength() {
        return halsteadLength;
    }

    /**
     * Sets the value of the halsteadLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHalsteadLength(BigInteger value) {
        this.halsteadLength = value;
    }

    /**
     * Gets the value of the halsteadVocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHalsteadVocabulary() {
        return halsteadVocabulary;
    }

    /**
     * Sets the value of the halsteadVocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHalsteadVocabulary(BigInteger value) {
        this.halsteadVocabulary = value;
    }

    /**
     * Gets the value of the halsteadBugs property.
     * 
     */
    public float getHalsteadBugs() {
        return halsteadBugs;
    }

    /**
     * Sets the value of the halsteadBugs property.
     * 
     */
    public void setHalsteadBugs(float value) {
        this.halsteadBugs = value;
    }

    /**
     * Gets the value of the halsteadDifficulty property.
     * 
     */
    public float getHalsteadDifficulty() {
        return halsteadDifficulty;
    }

    /**
     * Sets the value of the halsteadDifficulty property.
     * 
     */
    public void setHalsteadDifficulty(float value) {
        this.halsteadDifficulty = value;
    }

    /**
     * Gets the value of the halsteadEffort property.
     * 
     */
    public float getHalsteadEffort() {
        return halsteadEffort;
    }

    /**
     * Sets the value of the halsteadEffort property.
     * 
     */
    public void setHalsteadEffort(float value) {
        this.halsteadEffort = value;
    }

    /**
     * Gets the value of the halsteadVolume property.
     * 
     */
    public float getHalsteadVolume() {
        return halsteadVolume;
    }

    /**
     * Sets the value of the halsteadVolume property.
     * 
     */
    public void setHalsteadVolume(float value) {
        this.halsteadVolume = value;
    }

    /**
     * Gets the value of the classesReferenced property.
     * 
     * @return
     *     possible object is
     *     {@link ClassesReferencedType }
     *     
     */
    public ClassesReferencedType getClassesReferenced() {
        return classesReferenced;
    }

    /**
     * Sets the value of the classesReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassesReferencedType }
     *     
     */
    public void setClassesReferenced(ClassesReferencedType value) {
        this.classesReferenced = value;
    }

    /**
     * Gets the value of the externalMethodsCalled property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalMethodsCalledType }
     *     
     */
    public ExternalMethodsCalledType getExternalMethodsCalled() {
        return externalMethodsCalled;
    }

    /**
     * Sets the value of the externalMethodsCalled property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalMethodsCalledType }
     *     
     */
    public void setExternalMethodsCalled(ExternalMethodsCalledType value) {
        this.externalMethodsCalled = value;
    }

    /**
     * Gets the value of the localMethods property.
     * 
     * @return
     *     possible object is
     *     {@link LocalMethodsType }
     *     
     */
    public LocalMethodsType getLocalMethods() {
        return localMethods;
    }

    /**
     * Sets the value of the localMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalMethodsType }
     *     
     */
    public void setLocalMethods(LocalMethodsType value) {
        this.localMethods = value;
    }

    /**
     * Gets the value of the variablesDeclared property.
     * 
     * @return
     *     possible object is
     *     {@link VariablesDeclaredType }
     *     
     */
    public VariablesDeclaredType getVariablesDeclared() {
        return variablesDeclared;
    }

    /**
     * Sets the value of the variablesDeclared property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariablesDeclaredType }
     *     
     */
    public void setVariablesDeclared(VariablesDeclaredType value) {
        this.variablesDeclared = value;
    }

    /**
     * Gets the value of the variablesReferenced property.
     * 
     * @return
     *     possible object is
     *     {@link VariablesReferencedType }
     *     
     */
    public VariablesReferencedType getVariablesReferenced() {
        return variablesReferenced;
    }

    /**
     * Sets the value of the variablesReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariablesReferencedType }
     *     
     */
    public void setVariablesReferenced(VariablesReferencedType value) {
        this.variablesReferenced = value;
    }

    /**
     * Gets the value of the instanceVariablesReferenced property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceVariablesReferencedType }
     *     
     */
    public InstanceVariablesReferencedType getInstanceVariablesReferenced() {
        return instanceVariablesReferenced;
    }

    /**
     * Sets the value of the instanceVariablesReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceVariablesReferencedType }
     *     
     */
    public void setInstanceVariablesReferenced(InstanceVariablesReferencedType value) {
        this.instanceVariablesReferenced = value;
    }

    /**
     * Gets the value of the localInstanceVariablesReferenced property.
     * 
     * @return
     *     possible object is
     *     {@link LocalInstanceVariablesReferencedType }
     *     
     */
    public LocalInstanceVariablesReferencedType getLocalInstanceVariablesReferenced() {
        return localInstanceVariablesReferenced;
    }

    /**
     * Sets the value of the localInstanceVariablesReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalInstanceVariablesReferencedType }
     *     
     */
    public void setLocalInstanceVariablesReferenced(LocalInstanceVariablesReferencedType value) {
        this.localInstanceVariablesReferenced = value;
    }

    /**
     * Gets the value of the exceptionsReferenced property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionsReferencedType }
     *     
     */
    public ExceptionsReferencedType getExceptionsReferenced() {
        return exceptionsReferenced;
    }

    /**
     * Sets the value of the exceptionsReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionsReferencedType }
     *     
     */
    public void setExceptionsReferenced(ExceptionsReferencedType value) {
        this.exceptionsReferenced = value;
    }

    /**
     * Gets the value of the exceptionsThrown property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionsThrownType }
     *     
     */
    public ExceptionsThrownType getExceptionsThrown() {
        return exceptionsThrown;
    }

    /**
     * Sets the value of the exceptionsThrown property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionsThrownType }
     *     
     */
    public void setExceptionsThrown(ExceptionsThrownType value) {
        this.exceptionsThrown = value;
    }

    /**
     * Gets the value of the arguments property.
     * 
     * @return
     *     possible object is
     *     {@link ArgumentsType }
     *     
     */
    public ArgumentsType getArguments() {
        return arguments;
    }

    /**
     * Sets the value of the arguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArgumentsType }
     *     
     */
    public void setArguments(ArgumentsType value) {
        this.arguments = value;
    }

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiersType }
     *     
     */
    public ModifiersType getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiersType }
     *     
     */
    public void setModifiers(ModifiersType value) {
        this.modifiers = value;
    }

}
