//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.11 at 08:27:51 PM CET 
//


package at.qualisign.metrics.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jhawk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _System_QNAME = new QName("jhawk", "System");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jhawk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemType }
     * 
     */
    public SystemType createSystemType() {
        return new SystemType();
    }

    /**
     * Create an instance of {@link ExceptionsThrownType }
     * 
     */
    public ExceptionsThrownType createExceptionsThrownType() {
        return new ExceptionsThrownType();
    }

    /**
     * Create an instance of {@link ImportedPackagesType }
     * 
     */
    public ImportedPackagesType createImportedPackagesType() {
        return new ImportedPackagesType();
    }

    /**
     * Create an instance of {@link ClassesType }
     * 
     */
    public ClassesType createClassesType() {
        return new ClassesType();
    }

    /**
     * Create an instance of {@link InstanceVariablesType }
     * 
     */
    public InstanceVariablesType createInstanceVariablesType() {
        return new InstanceVariablesType();
    }

    /**
     * Create an instance of {@link PackagesType }
     * 
     */
    public PackagesType createPackagesType() {
        return new PackagesType();
    }

    /**
     * Create an instance of {@link InterfacesType }
     * 
     */
    public InterfacesType createInterfacesType() {
        return new InterfacesType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link PackageMetricsType }
     * 
     */
    public PackageMetricsType createPackageMetricsType() {
        return new PackageMetricsType();
    }

    /**
     * Create an instance of {@link MethodsType }
     * 
     */
    public MethodsType createMethodsType() {
        return new MethodsType();
    }

    /**
     * Create an instance of {@link MethodMetricsType }
     * 
     */
    public MethodMetricsType createMethodMetricsType() {
        return new MethodMetricsType();
    }

    /**
     * Create an instance of {@link ArgumentsType }
     * 
     */
    public ArgumentsType createArgumentsType() {
        return new ArgumentsType();
    }

    /**
     * Create an instance of {@link LocalMethodCallsType }
     * 
     */
    public LocalMethodCallsType createLocalMethodCallsType() {
        return new LocalMethodCallsType();
    }

    /**
     * Create an instance of {@link LocalMethodsType }
     * 
     */
    public LocalMethodsType createLocalMethodsType() {
        return new LocalMethodsType();
    }

    /**
     * Create an instance of {@link VariablesDeclaredType }
     * 
     */
    public VariablesDeclaredType createVariablesDeclaredType() {
        return new VariablesDeclaredType();
    }

    /**
     * Create an instance of {@link VariablesReferencedType }
     * 
     */
    public VariablesReferencedType createVariablesReferencedType() {
        return new VariablesReferencedType();
    }

    /**
     * Create an instance of {@link ExceptionsReferencedType }
     * 
     */
    public ExceptionsReferencedType createExceptionsReferencedType() {
        return new ExceptionsReferencedType();
    }

    /**
     * Create an instance of {@link CountableReferenceType }
     * 
     */
    public CountableReferenceType createCountableReferenceType() {
        return new CountableReferenceType();
    }

    /**
     * Create an instance of {@link MethodType }
     * 
     */
    public MethodType createMethodType() {
        return new MethodType();
    }

    /**
     * Create an instance of {@link ExternalMethodCallsType }
     * 
     */
    public ExternalMethodCallsType createExternalMethodCallsType() {
        return new ExternalMethodCallsType();
    }

    /**
     * Create an instance of {@link HierarchyMethodCallsType }
     * 
     */
    public HierarchyMethodCallsType createHierarchyMethodCallsType() {
        return new HierarchyMethodCallsType();
    }

    /**
     * Create an instance of {@link ModifiersType }
     * 
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link ClassesReferencedType }
     * 
     */
    public ClassesReferencedType createClassesReferencedType() {
        return new ClassesReferencedType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link TypedReferenceType }
     * 
     */
    public TypedReferenceType createTypedReferenceType() {
        return new TypedReferenceType();
    }

    /**
     * Create an instance of {@link ClassMetricsType }
     * 
     */
    public ClassMetricsType createClassMetricsType() {
        return new ClassMetricsType();
    }

    /**
     * Create an instance of {@link ExternalMethodsCalledType }
     * 
     */
    public ExternalMethodsCalledType createExternalMethodsCalledType() {
        return new ExternalMethodsCalledType();
    }

    /**
     * Create an instance of {@link LocalInstanceVariablesReferencedType }
     * 
     */
    public LocalInstanceVariablesReferencedType createLocalInstanceVariablesReferencedType() {
        return new LocalInstanceVariablesReferencedType();
    }

    /**
     * Create an instance of {@link InstanceVariablesReferencedType }
     * 
     */
    public InstanceVariablesReferencedType createInstanceVariablesReferencedType() {
        return new InstanceVariablesReferencedType();
    }

    /**
     * Create an instance of {@link LOCType }
     * 
     */
    public LOCType createLOCType() {
        return new LOCType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "jhawk", name = "System")
    public JAXBElement<SystemType> createSystem(SystemType value) {
        return new JAXBElement<SystemType>(_System_QNAME, SystemType.class, null, value);
    }

}
