//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.09 at 09:28:56 AM CEST 
//


package at.qualisign.metrics.ckjm.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.qualisign.metrics.ckjm.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ckjm_QNAME = new QName("", "ckjm");
    private final static QName _CcTypeMethod_QNAME = new QName("", "method");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.qualisign.metrics.ckjm.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CkjmType }
     * 
     */
    public CkjmType createCkjmType() {
        return new CkjmType();
    }

    /**
     * Create an instance of {@link CcType }
     * 
     */
    public CcType createCcType() {
        return new CcType();
    }

    /**
     * Create an instance of {@link MethodType }
     * 
     */
    public MethodType createMethodType() {
        return new MethodType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CkjmType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ckjm")
    public JAXBElement<CkjmType> createCkjm(CkjmType value) {
        return new JAXBElement<CkjmType>(_Ckjm_QNAME, CkjmType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "method", scope = CcType.class)
    public JAXBElement<MethodType> createCcTypeMethod(MethodType value) {
        return new JAXBElement<MethodType>(_CcTypeMethod_QNAME, MethodType.class, CcType.class, value);
    }

}
