version: '3.7'
services:
  arangodb:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data:
