package at.qualisign.domain

case class MethodMetricsJHawk(
  method: String,
  cyclomaticComplexity: Int,
  halsteadBugs: Double,
  halsteadDifficulty: Double,
  halsteadEffort: Double,
  halsteadLength: Int,
  halsteadVocabulary: Int,
  halsteadVolume: Double,
  loc: Int,
  maxDepthOfNesting: Int,
  numberOfArguments: Int,
  numberOfCasts: Int,
  numberOfCommentLines: Int,
  numberOfComments: Int,
  numberOfExpressions: Int,
  numberOfLoops: Int,
  numberOfOperands: Int,
  numberOfOperators: Int,
  numberOfStatements: Int,
  numberOfVariableDeclarations: Int,
  numberOfVariableReferences: Int,
  totalNesting: Int,
)
